---
- name: unload MacOS Apache
  command: launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist
  become: yes
  changed_when: false

- name: install taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/apache

- name: install Apache
  homebrew: name=httpd state=present

- name: create Apache configuration directory
  file: path=/usr/local/etc/httpd/other state=directory recurse=yes
  tags:
     - configuration

- name: enable other directory in Apache
  lineinfile: dest=/usr/local/etc/httpd/httpd.conf line="Include /usr/local/etc/httpd/other/*" state=present
  notify: restart apache
  tags:
     - configuration

- name: set Apache port
  lineinfile: dest=/usr/local/etc/httpd/httpd.conf regexp="^Listen " line="Listen 80" state=present
  notify: restart apache
  tags:
     - configuration

- name: configure Apache
  template: src=templates/httpd.conf.j2 dest=/usr/local/etc/httpd/other/httpd.conf
  notify: restart apache
  tags:
     - configuration

- name: enable PHP in Apache
  template: src=templates/php.conf.j2 dest=/usr/local/etc/httpd/other/php.conf
  notify: restart apache
  tags:
     - configuration

- name: configure Virtualhosts in Apache
  template: src=templates/vhosts.conf.j2 dest=/usr/local/etc/httpd/other/vhosts.conf
  notify: restart apache
  tags:
     - configuration

- name: update /etc/hosts
  lineinfile: dest=/etc/hosts regexp=".* {{ item.servername }}.*$" line="127.0.0.1 {{ item.servername }}{% if item.serveralias is defined %} {{ item.serveralias }}{% endif %}" state=present
  with_items: '{{ virtualhosts }}'
  become: yes
  tags:
     - configuration
