language: ruby
os: osx
osx_image: xcode9
rvm: system

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/.cache/pip

before_install:
  - brew update
  - brew install ansible

script:
  - ansible-playbook site.yml --syntax-check
  - ansible-playbook site.yml --diff

before_cache:
  - brew cleanup
