os: osx
osx_image: xcode10

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/.cache/pip

before_install:
  - brew update
  - brew unlink python
  - brew install ansible

script:
  - ansible-playbook site.yml --syntax-check
  - ansible-playbook site.yml --diff

before_cache:
  - brew cleanup
