language: ruby
os: osx
rvm: system

matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode7.1

cache:
  directories:
    - /Library/Caches/Homebrew
    - $HOME/.cache/pip

before_install:
  - brew update
  - brew install ansible

script:
  - ansible-playbook site.yml --syntax-check
  - ansible-playbook site.yml --diff -vvv

before_cache:
  - brew cleanup
