language: ruby
os: osx
osx_image: xcode7.3
rvm: system

cache:
  directories:
    - /Library/Caches/Homebrew
    - $HOME/.cache/pip

before_install:
  - brew update
  - brew install ansible

script:
  - ansible-playbook site.yml --syntax-check
  - ansible-playbook site.yml --diff

before_cache:
  - brew cleanup
