---
- hosts: localhost
  connection: local

  roles:
    - apps
    - atom
    - dotfiles
    - ssh
    - macos
    - php
    - role: sdkman
      sdkman_dir: /usr/local/sdkman
      sdkman_auto_answer: true
      sdkman_update: true
      sdkman_install_packages:
      - { candidate: java, version: '11.0.5.hs-adpt' }
