---

- name: create SSH directory if needed
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: configure SSH
  template: src=templates/config.j2 dest=~/.ssh/config
  tags:
     - configuration
