---
- name: install taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/cask
    - homebrew/cask-fonts
    - cloudfoundry/tap

- name: install prerequisite casks
  homebrew_cask: name={{ item }} state=present
  when: not lookup("env", "CI")
  ignore_errors: yes
  with_items:
    # for maven
    - java

- name: install brews
  homebrew: name={{ item }} state=present
  ignore_errors: yes
  with_items:
    - git
    - python
    - mas
    - maven
    - node
    - yarn
    - rbenv
    - ruby
    - wget
    - cf-cli
    - liquibase
    - mongodb
    - maven

- name: install Memcached
  homebrew: name=memcached state=present
  notify: restart memcached

- name: install MySQL
  homebrew: name=mysql@5.7 state=present
  notify: restart mysql

- name: get installed apps from app store
  command: mas list
  when: not lookup("env", "CI")
  register: mas_result
  check_mode: no
  changed_when: false

- name: install apps from app store
  command: mas install {{ item }}
  ignore_errors: yes
  when: not mas_result.skipped|default(false) and item|string not in mas_result.stdout
  with_items: "{{ app_store_apps }}"

- name: install casks
  homebrew_cask: name={{ item }} state=present
  when: not lookup("env", "CI")
  ignore_errors: yes
  with_items: "{{ cask_apps }}"
# - name: install npm packages
#   npm: name={{ item }} global=yes state=present
#   with_items:
#     - bower
