---
- name: install taps
  homebrew_tap: tap={{ item }} state=present
  with_items: '{{ homebrew_taps }}' 

- name: install brews
  homebrew: name={{ item }} state=present
  ignore_errors: yes
  with_items: '{{ homebrew_packages }}'

- name: get installed apps from app store
  command: mas list
  when: not lookup("env", "CI")
  register: mas_result
  check_mode: no
  changed_when: false

- name: install apps from app store
  command: mas install {{ item }}
  ignore_errors: yes
  when: not mas_result.skipped|default(false) and item|string not in mas_result.stdout
  with_items: '{{ app_store_apps }}'

- name: install casks
  homebrew_cask: name={{ item }} state=present
  when: not lookup("env", "CI")
  ignore_errors: yes
  with_items: '{{ cask_apps }}'
