---
- name: install taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/dupes
    - homebrew/homebrew-php
    - homebrew/versions

- name: install brews
  homebrew: name={{ item }} state=present install_options={{ "with-apache" if not lookup("env", "CI") else "" }}
  ignore_errors: yes
  with_items:
    - php56
    - php56-intl
    - php56-xdebug
    - composer
  notify: restart apache

- name: configure PHP
  template: src=templates/php.ini.j2 dest=/usr/local/etc/php/5.6/conf.d/php.ini
  become: yes
  notify: restart apache
  tags:
     - configuration
