---
- name: install brews
  homebrew: name={{ item }} state=present install_options={{ "with-httpd" if not lookup("env", "CI") else "" }}
  ignore_errors: yes
  with_items:
    - php@7.4
    - composer
  notify: restart apache

- name: configure PHP
  template: src=templates/php.ini.j2 dest=/usr/local/etc/php/7.4/conf.d/php.ini
  become: yes
  notify: restart apache
  tags:
     - configuration
