---
- name: install taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/homebrew-php

- name: install brews
  homebrew: name={{ item }} state=present install_options={{ "with-httpd" if not lookup("env", "CI") else "" }}
  ignore_errors: yes
  with_items:
    - php71
    - php71-intl
    - php71-xdebug
    - composer
  notify: restart apache

- name: configure PHP
  template: src=templates/php.ini.j2 dest=/usr/local/etc/php/7.1/conf.d/php.ini
  become: yes
  notify: restart apache
  tags:
     - configuration
